version: 0.1

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "YOUR_AWS_REGION_CODE"
    HUGO_VERSION: "0.25.1"
    
phases:
  install:
    commands:                                                                 
      - cd /tmp
      - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - tar -xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - mv hugo /usr/bin/hugo
      - cd - 
      - rm -rf /tmp/*
  build:
    commands:
      - hugo
  post_build:
    commands:
      - aws s3 sync --delete public s3://pozitiff.mort-vivant.me --region eu-central-1 --cache-control max-age=604800
      - echo Build completed on `date`
      - aws sns publish --topic-arn $SNS_ARN_subject --TOPIC 'AWS CodeBuild - Build Completed'
 --message 'The build has completed. 
